# ENVIRONMENT
# Make sure ready for this project

# Change when R uses scientific notation
options(scipen=10)

# Create directory to be used later on if it doesnt exist
ifelse(!dir.exists(file.path(".", "tmp")), dir.create(file.path(".", "tmp")), FALSE)

# Clean up the files that are generated by running this project to make sure
#   they are generated fresh on each execution
# file <- "tmp/q1_plot.png"
# if (file.exists(file)) file.remove(file)

# file <- "tmp/q2_text.txt"
# if (file.exists(file)) file.remove(file)

# Make sure we have installed all needed Libraries
#
# Function taken from:  https://gist.github.com/smithdanielle/9913897
#
# check.packages function: install and load multiple R packages.
# Check to see if packages are installed. Install them if they are not, then load them into the R session.
check.packages <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, repos=c("http://archive.linux.duke.edu/cran/"), dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}

packages<-c( "dplyr", "ggplot2", "doBy", "stringr", "reshape2", "gridExtra", "gplots", "randomForest", "caret")
check.packages(packages)
